// Включи true, чтобы видеть области клика при настройке координат.
export const DETAIL_SCENE_DEBUG = {
  showHotspotBounds: false,
};

export const DETAIL_SCENES = {
  mesto1: {
    sceneId: "mesto1",
    title: "Рабочее место 1",
    image: "assets/scens/scen_mesto1.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "passwords_notebook",
        title: "Ежедневник с паролями",
        score: 15,
        x: 0.645,
        y: 0.55,
        w: 0.235,
        h: 0.225,
      },
      {
        id: "router_admin_admin",
        title: "Роутер с логином admin/admin",
        score: 15,
        x: 0.05,
        y: 0.38,
        w: 0.165,
        h: 0.12,
      },
      {
        id: "antivirus_delete",
        title: "Удаление антивируса на экране",
        score: 20,
        x: 0.46,
        y: 0.06,
        w: 0.3,
        h: 0.3,
      },
    ],
  },
  mesto2: {
    sceneId: "mesto2",
    title: "Рабочее место 2",
    image: "assets/scens/scen_mesto2.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "torrent_download",
        title: "Скачивание торрентов на рабочем ПК",
        score: 20,
        x: 0.43,
        y: 0.05,
        w: 0.375,
        h: 0.345,
      },
      {
        id: "unlocked_work_messenger",
        title: "Разблокированный телефон с рабочим мессенджером",
        score: 15,
        x: 0.032,
        y: 0.465,
        w: 0.08,
        h: 0.215,
      },
      {
        id: "lost_ubikey",
        title: "UbiKey валяется под столом",
        score: 20,
        x: 0.61,
        y: 0.88,
        w: 0.08,
        h: 0.08,
      },
    ],
  },
  mesto3: {
    sceneId: "mesto3",
    title: "Рабочее место 3",
    image: "assets/scens/scen_mesto3.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "unlocked_desktop",
        title: "Незаблокированный компьютер",
        score: 15,
        x: 0.125,
        y: 0.07,
        w: 0.32,
        h: 0.3,
      },
      {
        id: "password_on_sticker",
        title: "Пароль на стикере",
        score: 15,
        x: 0.16,
        y: 0.38,
        w: 0.08,
        h: 0.1,
      },
      {
        id: "flash_drive_reports",
        title: "Флешка с отчётами на столе",
        score: 20,
        x: 0.165,
        y: 0.61,
        w: 0.09,
        h: 0.08,
      },
      {
        id: "wifi_password_in_trash",
        title: "Пароль от Wi-Fi в урне",
        score: 20,
        x: 0.01,
        y: 0.77,
        w: 0.18,
        h: 0.15,
      },
      {
        id: "bank_card_in_drawer",
        title: "Банковская карта в открытом ящике",
        score: 15,
        x: 0.63,
        y: 0.855,
        w: 0.15,
        h: 0.11,
      },
      {
        id: "keys_in_drawer",
        title: "Ключи в открытом ящике",
        score: 15,
        x: 0.80,
        y: 0.86,
        w: 0.12,
        h: 0.12,
      },
    ],
  },
  mesto4: {
    sceneId: "mesto4",
    title: "Рабочее место 4",
    image: "assets/scens/scen_mesto4.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "passwords_in_trash",
        title: "Пароли в урне",
        score: 25,
        x: 0.045,
        y: 0.6,
        w: 0.15,
        h: 0.3,
      },
    ],
  },
  mesto5: {
    sceneId: "mesto5",
    title: "Рабочее место 5",
    image: "assets/scens/scen_mesto5.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "phishing_email",
        title: "Фишинговое письмо на почте",
        score: 20,
        x: 0.42,
        y: 0.06,
        w: 0.35,
        h: 0.3,
      },
      {
        id: "badge_out_of_pocket",
        title: "Пропуск висит из кармана",
        score: 20,
        x: 0.365,
        y: 0.76,
        w: 0.08,
        h: 0.15,
      },
    ],
  },
  stol_peregovorka: {
    sceneId: "stol_peregovorka",
    title: "Стол в переговорке",
    image: "assets/scens/scen_stol_peregovorka.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "forgotten_laptop",
        title: "Забытый ноутбук",
        score: 25,
        x: 0.065,
        y: 0.235,
        w: 0.235,
        h: 0.33,
      },
    ],
  },
  urna_mfu: {
    sceneId: "urna_mfu",
    title: "Урна рядом с МФУ",
    image: "assets/scens/scen_urna.png",
    width: 1086,
    height: 1448,
    hotspots: [
      {
        id: "passport_data_prints",
        title: "Паспортные данные выброшены без уничтожения",
        score: 30,
        x: 0.19,
        y: 0.225,
        w: 0.62,
        h: 0.34,
      },
    ],
  },
  divan: {
    sceneId: "divan",
    title: "Диван в зоне отдыха",
    image: "assets/scens/scen_divan.png",
    width: 1536,
    height: 1024,
    hotspots: [
      {
        id: "forgotten_badge",
        title: "Забытый пропуск сотрудника",
        score: 20,
        x: 0.51,
        y: 0.44,
        w: 0.1,
        h: 0.18,
      },
    ],
  },
};

export const DETAIL_SCENE_ITEM_IDS = new Set(Object.keys(DETAIL_SCENES));
