export const BASE_SCENE = {
  width: 1536,
  height: 1024,
  mapImage: "assets/karta.png",
};

export const SCENE_ITEMS = [
  {
    id: "vyveska_logo_company",
    name: "Вывеска компании",
    file: "assets/vyveska_logo_company.png",
    x: 130,
    y: 90,
    width: 200,
    z: 10,
    effect: {
      type: "neonBlink",
      periodMs: 2100,
      activeMs: 980,
    },
  },
  {
    id: "tablo_exit",
    name: "Табло «Выход»",
    file: "assets/tablo_exit.png",
    x: 364,
    y: 85,
    width: 96,
    z: 11,
  },
  {
    id: "plakat_volk",
    name: "Плакат «Работа не волк»",
    file: "assets/plakat_volk.png",
    x: 475,
    y: 92,
    width: 92,
    z: 5,
  },
  {
    id: "plakat_mem",
    name: "Плакат с мемом",
    file: "assets/plakat_mem.png",
    x: 980,
    y: 95,
    width: 92,
    z: 10,
  },
  {
    id: "tablo_tualet",
    name: "Табличка «Туалет»",
    file: "assets/tablo_tualet.png",
    x: 1086,
    y: 105,
    width: 80,
    z: 11,
  },
  {
    id: "kamera",
    name: "Камера наблюдения",
    file: "assets/kamera.png",
    x: 1384,
    y: 78,
    width: 36,
    z: 12,
  },
  {
    id: "kuller",
    name: "Кулер",
    file: "assets/kuller.png",
    x: 115,
    y: 190,
    width: 30,
    z: 18,
  },
  {
    id: "cvetok_left",
    name: "Цветок (слева)",
    file: "assets/cvetok.png",
    x: 130,
    y: 168,
    width: 54,
    z: 10,
  },
  {
    id: "reception",
    name: "Ресепшен",
    file: "assets/reception.png",
    x: 160,
    y: 236,
    width: 170,
    z: 22,
  },
  {
    id: "rabotik6",
    name: "Работник 6 (ресепшен)",
    frames: [
      "assets/persons/rabotik6/uniform/1.png",
      "assets/persons/rabotik6/uniform/2.png",
      "assets/persons/rabotik6/uniform/3.png",
      "assets/persons/rabotik6/uniform/4.png",
      "assets/persons/rabotik6/uniform/5.png",
      "assets/persons/rabotik6/uniform/6.png",
      "assets/persons/rabotik6/uniform/7.png",
      "assets/persons/rabotik6/uniform/8.png",
    ],
    frameDurationMs: 1070,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 235,
    y: 195,
    width: 56,
    z: 21,
  },
  {
    id: "ognetushitel",
    name: "Огнетушитель",
    file: "assets/ognetushitel.png",
    x: 331,
    y: 148,
    width: 28,
    z: 23,
  },
  {
    id: "mesto1",
    name: "Рабочее место 1",
    file: "assets/mesto1.png",
    x: 545,
    y: 260,
    width: 155,
    z: 30,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "code",
          // Нормализованные координаты зоны экрана внутри объекта:
          // x/y — левый верхний угол, w/h — ширина/высота (диапазон 0..1).
          x: 0.3,
          y: 0.01,
          w: 0.30,
          h: 0.25,
          lines: 16,
        },
      ],
    },
  },
  {
    id: "rabotik3",
    name: "Работник 3",
    frames: [
      "assets/persons/rabotik3/uniform/1.png",
      "assets/persons/rabotik3/uniform/2.png",
      "assets/persons/rabotik3/uniform/3.png",
      "assets/persons/rabotik3/uniform/4.png",
      "assets/persons/rabotik3/uniform/5.png",
      "assets/persons/rabotik3/uniform/6.png",
      "assets/persons/rabotik3/uniform/7.png",
      "assets/persons/rabotik3/uniform/8.png",
    ],
    frameDurationMs: 170,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 566,
    y: 252,
    width: 76,
    z: 34,
  },
  {
    id: "mesto2",
    name: "Рабочее место 2",
    file: "assets/mesto2.png",
    x: 728,
    y: 266,
    width: 158,
    z: 40,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "windows",
          x: 0.3,
          y: 0.01,
          w: 0.29,
          h: 0.23,
        },
      ],
    },
  },
  {
    id: "rabotik1",
    name: "Работник 1",
    frames: [
      "assets/persons/rabotik1/uniform/1.png",
      "assets/persons/rabotik1/uniform/2.png",
      "assets/persons/rabotik1/uniform/3.png",
      "assets/persons/rabotik1/uniform/4.png",
      "assets/persons/rabotik1/uniform/5.png",
      "assets/persons/rabotik1/uniform/6.png",
      "assets/persons/rabotik1/uniform/7.png",
      "assets/persons/rabotik1/uniform/8.png",
    ],
    frameDurationMs: 170,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 736,
    y: 256,
    width: 76,
    z: 44,
  },
  {
    id: "mesto3",
    name: "Рабочее место 3",
    file: "assets/mesto3.png",
    x: 890,
    y: 443,
    width: 180,
    z: 50,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "desktopStatic",
          x: 0.26,
          y: 0.01,
          w: 0.24,
          h: 0.23,
        },
        {
          mode: "desktopStatic",
          x: 0.52,
          y: 0.01,
          w: 0.24,
          h: 0.23,
        },
      ],
    },
  },
  {
    id: "rabotik2",
    name: "Работник 2",
    frames: [
      "assets/persons/rabotik2/uniform/1.png",
      "assets/persons/rabotik2/uniform/2.png",
      "assets/persons/rabotik2/uniform/3.png",
      "assets/persons/rabotik2/uniform/4.png",
      "assets/persons/rabotik2/uniform/5.png",
      "assets/persons/rabotik2/uniform/6.png",
      "assets/persons/rabotik2/uniform/7.png",
      "assets/persons/rabotik2/uniform/8.png",
    ],
    frameDurationMs: 170,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 936,
    y: 255,
    width: 70,
    z: 54,
  },
  {
    id: "kreslo_mesto3",
    name: "Кресло (рабочее место 3)",
    file: "assets/kreslo.png",
    x: 960,
    y: 484,
    width: 50,
    z: 53,
  },
  {
    id: "holodiln",
    name: "Холодильник",
    file: "assets/holodiln.png",
    x: 1185,
    y: 92,
    width: 56,
    z: 11,
  },
  {
    id: "kugnya",
    name: "Кухонная зона",
    file: "assets/kugnya.png",
    x: 1240,
    y: 145,
    width: 190,
    z: 15,
  },
  {
    id: "rabotik5",
    name: "Работник 5 (кухня)",
    frames: [
      "assets/persons/rabotik5/uniform/1.png",
      "assets/persons/rabotik5/uniform/2.png",
      "assets/persons/rabotik5/uniform/3.png",
      "assets/persons/rabotik5/uniform/4.png",
      "assets/persons/rabotik5/uniform/5.png",
      "assets/persons/rabotik5/uniform/6.png",
      "assets/persons/rabotik5/uniform/7.png",
      "assets/persons/rabotik5/uniform/8.png",
    ],
    frameDurationMs: 2000,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 1295,
    y: 185,
    width: 75,
    z: 23,
  },
  {
    id: "stol_kuhnya",
    name: "Круглый стол на кухне",
    file: "assets/stol_kuhnya.png",
    x: 1224,
    y: 266,
    width: 175,
    z: 24,
    effect: {
      type: "pizzaSteam",
      lifeMs: 2500,
      anchors: [{ x: 0.33, y: 0.28, plumes: 4 }],
    },
  },
  {
    id: "cvetok_kitchen",
    name: "Цветок (у кухни)",
    file: "assets/cvetok2.png",
    x: 1048,
    y: 190,
    width: 41,
    z: 22,
  },
  {
    id: "divan",
    name: "Диван",
    file: "assets/divan.png",
    x: 107,
    y: 324,
    width: 130,
    z: 26,
  },
  {
    id: "stol_reception",
    name: "Журнальный столик",
    file: "assets/stol_reception.png",
    x: 170,
    y: 403,
    width: 162,
    z: 27,
  },
  {
    id: "kvas_automat",
    name: "Автомат с квасом",
    file: "assets/kvas_automat.png",
    x: 101,
    y: 426,
    width: 121,
    z: 28,
  },
  {
    id: "urna_mfu",
    name: "Урна",
    file: "assets/urna_mfu.png",
    x: 780,
    y: 500,
    width: 32,
    z: 20,
  },
  {
    id: "cvetok_center",
    name: "Цветок (в центре)",
    file: "assets/cvetok.png",
    x: 452,
    y: 467,
    width: 50,
    z: 17,
  },
  {
    id: "mesto4",
    name: "Рабочее место 4",
    file: "assets/mesto4.png",
    x: 515,
    y: 447,
    width: 150,
    z: 35,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "game",
          x: 0.3,
          y: 0.001,
          w: 0.31,
          h: 0.31,
        },
      ],
    },
  },
  {
    id: "rabotik4",
    name: "Работник 4",
    frames: [
      "assets/persons/rabotik4/1.png?v=20260515c2",
      "assets/persons/rabotik4/2.png?v=20260515c2",
      "assets/persons/rabotik4/3.png?v=20260515c2",
      "assets/persons/rabotik4/4.png?v=20260515c2",
      "assets/persons/rabotik4/5.png?v=20260515c2",
      "assets/persons/rabotik4/6.png?v=20260515c2",
      "assets/persons/rabotik4/7.png?v=20260515c2",
      "assets/persons/rabotik4/8.png?v=20260515c2",
    ],
    frameDurationMs: 170,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 520,
    y: 445,
    width: 80,
    z: 39,
  },
  {
    id: "mesto5",
    name: "Рабочее место 5",
    file: "assets/mesto5.png",
    x: 916,
    y: 265,
    width: 160,
    z: 45,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "desktop",
          x: 0.3,
          y: 0.01,
          w: 0.30,
          h: 0.29,
        },
      ],
    },
  },
  {
    id: "ograzdenya",
    name: "Ограждения рабочих мест",
    file: "assets/ograzdenya.png",
    x: 490,
    y: 250,
    width: 606,
    z: 26,
    interactive: false,
  },
  {
    id: "mfu",
    name: "МФУ",
    file: "assets/mfu.png",
    x: 728,
    y: 438,
    width: 55,
    z: 30,
  },
  {
    id: "yashik",
    name: "Ящик",
    file: "assets/yashik.png",
    x: 681,
    y: 480,
    width: 40,
    z: 29,
  },
  {
    id: "tablichka_peregovorka",
    name: "Табличка «Переговорная»",
    file: "assets/tablichka_peregovorka.png",
    x: 1128,
    y: 411,
    width: 75,
    z: 31,
  },
  {
    id: "mitre_doska",
    name: "Доска MITRE ATT&CK",
    file: "assets/mitre_doska.png",
    x: 1209,
    y: 410,
    width: 218,
    z: 30,
  },
  {
    id: "stol_peregovorka",
    name: "Стол переговорки",
    file: "assets/stol_peregovorka.png",
    x: 1188,
    y: 520,
    width: 280,
    z: 32,
  },
  {
    id: "tablo_servernaya",
    name: "Табло «Серверная»",
    file: "assets/tablo_servernaya.png",
    x: 250,
    y: 728,
    width: 90,
    z: 35,
  },
  {
    id: "servernaya",
    name: "Серверные стойки",
    file: "assets/servernaya.png",
    x: 346,
    y: 665,
    width: 315,
    z: 36,
    effect: {
      type: "serverSparks",
      periodMs: 1050,
      burstMs: 760,
      anchorX: 0.57,
      anchorY: 0.1,
      sparks: 9,
      sizeScale: 1.9,
    },
  },
  {
    id: "comp_servernaya",
    name: "Стол в серверной",
    file: "assets/comp_servernaya.png",
    x: 570,
    y: 802,
    width: 134,
    z: 37,
    effect: {
      type: "monitorActivity",
      screens: [
        {
          mode: "alert",
          x: 0.30,
          y: 0.05,
          w: 0.35,
          h: 0.25,
        },
      ],
    },
  },
  {
    id: "rabotik7",
    name: "Работник 7 (серверная)",
    frames: [
      "assets/persons/rabotik7/uniform/1.png",
      "assets/persons/rabotik7/uniform/2.png",
      "assets/persons/rabotik7/uniform/3.png",
      "assets/persons/rabotik7/uniform/4.png",
      "assets/persons/rabotik7/uniform/5.png",
      "assets/persons/rabotik7/uniform/6.png",
      "assets/persons/rabotik7/uniform/7.png",
      "assets/persons/rabotik7/uniform/8.png",
    ],
    frameDurationMs: 1070,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 615,
    y: 795,
    width: 92,
    z: 38,
  },
  {
    id: "tablo_soc",
    name: "Табло SOC",
    file: "assets/tablo_soc.png",
    x: 736,
    y: 728,
    width: 100,
    z: 35,
  },
  {
    id: "plokat_soc",
    name: "Плакат SOC: угрозы безопасности",
    file: "assets/plokat_soc.png",
    x: 1220,
    y: 678,
    width: 165,
    z: 34,
  },
  {
    id: "plokat2_soc",
    name: "Плакат SOC: процесс инцидента",
    file: "assets/plokat2_soc.png",
    x: 1390,
    y: 678,
    width: 105,
    z: 34,
  },
  {
    id: "rabotik8",
    name: "Работник 8 (SOC, диалог)",
    frames: [
      "assets/persons/rabotik8/uniform/1.png",
      "assets/persons/rabotik8/uniform/2.png",
      "assets/persons/rabotik8/uniform/3.png",
      "assets/persons/rabotik8/uniform/4.png",
      "assets/persons/rabotik8/uniform/5.png",
      "assets/persons/rabotik8/uniform/6.png",
      "assets/persons/rabotik8/uniform/7.png",
      "assets/persons/rabotik8/uniform/8.png",
    ],
    frameDurationMs: 700,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 1030,
    y: 790,
    width: 140,
    z: 38,
  },
  {
    id: "rabotik9",
    name: "Работник 9 (SOC)",
    frames: [
      "assets/persons/rabotik9/uniform/1.png",
      "assets/persons/rabotik9/uniform/2.png",
      "assets/persons/rabotik9/uniform/3.png",
      "assets/persons/rabotik9/uniform/4.png",
      "assets/persons/rabotik9/uniform/5.png",
      "assets/persons/rabotik9/uniform/6.png",
      "assets/persons/rabotik9/uniform/7.png",
      "assets/persons/rabotik9/uniform/8.png",
    ],
    frameDurationMs: 170,
    alignX: "left",
    alignY: "bottom",
    normalizeContentScale: true,
    contentHeightStrategy: "max",
    x: 880,
    y: 795,
    width: 75,
    z: 38,
  },
  {
    id: "soc_stol_and_monitors",
    name: "Пульт SOC",
    file: "assets/soc_stol_and_monitors.png",
    x: 859,
    y: 678,
    width: 375,
    z: 36,
  },
  {
    id: "shkaf_soc",
    name: "Шкаф SOC",
    file: "assets/shkaf_soc.png",
    x: 1330,
    y: 742,
    width: 150,
    z: 37,
  },
];
